// <auto-generated />
namespace Ltd.NA.Emlak.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HouseMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HouseMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201506191908242_HouseMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
